#!/bin/sh

WORKER="$PWD/worker"
CMDP="/opt/exec_cmd"
CMDF="$WORKER/$CMDP"

ulimit -t 10
ulimit -f 10000
ulimit -d 10000
ulimit -m 1024
ulimit -v 80960
ulimit -u 50
ulimit -x 50

user="$1"
shift


uid=$(chroot --userspec=0 "$WORKER" /bin/sh -c "id -u $user 2>/dev/null")

if [ -z "$uid" ]; then
	echo "Adding new user ${user}... Welcome to POSIX sh SH-bot! USAGE info on: ftp://neverb.net/doc/shbot/shbot.txt"
	chroot --userspec=0 "$WORKER" /bin/sh -c "useradd -m $user"
	uid=$(chroot --userspec=0 "$WORKER" /bin/sh -c "id -u $user 2>/dev/null")	
fi


echo '#!/bin/sh' > "$CMDF"
echo "HOME=/home/$user" >> "$CMDF"
echo "LOGNAME=$user" >> "$CMDF"
echo "MAIL=$user/.mail" >> "$CMDF"
echo "SUDO_COMMAND='hacker'" >> "$CMDF"
echo "USER=$user" >> "$CMDF"
echo "USERNAME=$user" >> "$CMDF"

echo 'ulimit -t 10' >> "$CMDF"
#echo 'ulimit -f 9000' >> "$CMDF"
echo 'ulimit -d 9000' >> "$CMDF"
echo 'ulimit -m 1024' >> "$CMDF"
echo 'ulimit -v 80960' >> "$CMDF"
echo 'ulimit -u 50' >> "$CMDF"
echo 'ulimit -x 50' >> "$CMDF"
echo "cd /home/$user" >> "$CMDF"
echo "$@" >> "$CMDF"

timeout 1 chroot --userspec=$uid "$WORKER" /bin/sh -c "bash $CMDP 2>&1 | head -c 10240 | sed 's|^$CMDP: line [0-9]*: ||g'" 2>/dev/null || { echo "Terminated"; }
#timeout 1 chroot --userspec=$uid "$WORKER" /bin/sh -c "bash $CMDP 2>&1 | head -c 10240"

size=$(du -s "$WORKER/home/$user" | awk '{print $1}')
count=$(ls -1 "$WORKER/home/$user" | wc -l)

if [ $size -gt 5000 ]; then
	echo "Too many large files. Cleaning up."
	rm -r "$WORKER/home/$user/"*
fi

if [ $count -gt 100 ]; then
	echo "Too many files. Cleaning up."
	rm -r "$WORKER/home/$user/"*
fi

